[font.normal]
family = "Cascadia Mono"
style = "Regular"

[window]
opacity = 0.8
decorations = "none"
dynamic_padding = true
blur = true

[window.padding]
x = 5
y = 5

[general]
import = [
	"~/.config/alacritty/themes/gruvbox.toml"
]

