[theme]
theme = "gruvbox-dark"

#[[block]]
#block = "custom"
#command = "swaymsg -t get_tree | jq -r '.. | select(.focused?) | .name'"
#interval = 0.5

[[block]]
block = "sound"
step_width = 5
format = " $icon {$volume|} ┇"

[[block]]
block = "time"
interval = 60
format = "$timestamp.datetime(f:'%a %d/%m ┇ %R') "
