#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d main term web misc music

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Set the border colors.
bspc config normal_border_color "#818375"
bspc config active_border_color "#928374"
#bspc config focused_border_color "#dbcfc6"
bspc config focused_border_color "#EBDBB2"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "#818375"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
